### ISSUE TITLE
大神， 怎么build iso呀？

### ISSUE THREAD

**Issue by stonexing** [athlonreg/Clover_Build#3]
使用@Micky1979
的脚本可以自动化编译创建最新版的Clover pkg文件
但是我需要的是定制的iso文件（尝试UltraISO和7z做的都出问题）
求指导楼主的iso是如何打包得到呢？

**Comment by athlonreg** [comment]
在用户根目录下有一个脚本的配置文件，叫BuildClover什么的，里面有一个编译iso文件的配置项，把它打开就可以了

**Comment by stonexing** [comment]
好的 非常感谢 
但是我测了那个方法是没用用的 无论修改里边的build iso为YES 还是修改配置文件为YES均无效

正确方法是修改项目https://github.com/Micky1979/Build_Clover中的Build_Clover.command
在local options=()后边加一行代码
options+=("build iso")
这样就可以build iso了
